
########################################################################
# ウェブページの HTML を保管する API サーバー
# 直接の目的は、www.tcpdetective.com の各ページを Googlebot などのクローラーが取得できるようにすることだが、このサービスは汎用化できる。
# ん？需要無い？
########################################################################

# 開発環境一番機
<VirtualHost *:80>
    ServerAdmin kisaburo@starship.jp
    DocumentRoot /var/www/prerender-dev.starship.jp
    ServerName prerender-dev1.starship.jp
    ErrorLog logs/prerender-dev1.starship.jp-error_log
    CustomLog logs/prerender-dev1.starship.jp-access_log common
    <Directory /var/www/prerender-dev.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
#RewriteEngine on
#RewriteCond %{SERVER_NAME} =prerender-dev1.starship.jp
#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

# 開発環境 LB
<VirtualHost *:80>
    ServerAdmin kisaburo@starship.jp
    DocumentRoot /var/www/prerender-dev.starship.jp
    ServerName prerender-dev.starship.jp
    ErrorLog logs/prerender-dev.starship.jp-error_log
    CustomLog logs/prerender-dev.starship.jp-access_log common
    <Directory /var/www/prerender-dev.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
</VirtualHost>
