
########################################################################
# starship.jp ブランド（＝ポートフォリオ＝ショーケース）サイト内部 API サーバー開発環境
########################################################################

################
# 1 番機
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi-dev.starship.jp
    ServerName priapi-dev1.starship.jp
    ErrorLog logs/priapi-dev1.starship.jp-error_log
    CustomLog logs/priapi-dev1.starship.jp-access_log common
    <Directory /var/www/priapi-dev.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
</VirtualHost>

################
# LB 経由
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi-dev.starship.jp
    ServerName priapi-dev.starship.jp
    ErrorLog logs/priapi-dev.starship.jp-error_log
    CustomLog logs/priapi-dev.starship.jp-access_log common
    <Directory /var/www/priapi-dev.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
# 証明書をインストールすると、ここに余計なお世話がまた挿入される予定
</VirtualHost>

########################################################################
# starship.jp ブランド（＝ポートフォリオ＝ショーケース）サイト内部 API サーバーβ環境
########################################################################

################
# 1 番機
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi-beta.starship.jp
    ServerName priapi-beta1.starship.jp
    ErrorLog logs/priapi-beta1.starship.jp-error_log
    CustomLog logs/priapi-beta1.starship.jp-access_log common
    <Directory /var/www/priapi-beta.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
# 証明書をインストールすると、ここに余計なお世話がまた挿入される予定
</VirtualHost>

################
# LB 経由
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi-beta.starship.jp
    ServerName priapi-beta.starship.jp
    ErrorLog logs/priapi-beta.starship.jp-error_log
    CustomLog logs/priapi-beta.starship.jp-access_log common
    <Directory /var/www/priapi-beta.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
# 証明書をインストールすると、ここに余計なお世話がまた挿入される予定
</VirtualHost>

########################################################################
# starship.jp ブランド（＝ポートフォリオ＝ショーケース）サイト内部 API サーバー商用環境
########################################################################

################
# 1 番機
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi.starship.jp
    ServerName priapi1.starship.jp
    ErrorLog logs/priapi1.starship.jp-error_log
    CustomLog logs/priapi1.starship.jp-access_log common
    <Directory /var/www/priapi.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
# 証明書をインストールすると、ここに余計なお世話がまた挿入される予定
</VirtualHost>

################
# LB 経由
<VirtualHost *:80>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/priapi.starship.jp
    ServerName priapi.starship.jp
    ErrorLog logs/priapi.starship.jp-error_log
    CustomLog logs/priapi.starship.jp-access_log common
    <Directory /var/www/priapi.starship.jp>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
# 証明書をインストールすると、ここに余計なお世話がまた挿入される予定
</VirtualHost>
