# Googlebot 用スタティックページサイト。

Listen 8080

<VirtualHost *:8080>
    ServerAdmin ishioka@starship.jp
    DocumentRoot /var/www/www.starship.jp/_static
    ErrorLog logs/static-error_log
    CustomLog logs/static-access_log common
    <Directory /var/www/www.starship.jp/_static>
        Options FollowSymLinks
        AllowOverride All
    </Directory>
</VirtualHost>
