#
# PHP is an HTML-embedded scripting language which attempts to make it
# easy for developers to write dynamically generated webpages.
#

# Cannot load multiple php modules
<IfModule !mod_php5.c>
    <IfModule !mod_php7.c>
        <IfModule prefork.c>
            LoadModule php_module modules/libphp.so
        </IfModule>
    </IfModule>
</IfModule>



<IfModule !mod_php5.c>
  <IfModule !mod_php7.c>
    <IfModule !prefork.c>
      # The ZTS module is not the supported method of executing
      # PHP under apache, use the php-fpm package instead.
      #
      # https://wiki.apache.org/httpd/PHP-FPM
      LoadModule php_module modules/libphp-zts.so
    </IfModule>
  </IfModule>
</IfModule>
